kind: Template
apiVersion: v1
template: zeppelin
metadata:
  name: zeppelin
objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: zeppelin-web
    labels:
      name: zeppelin
  spec:
    ports:
      - name: zeppelin-web
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      name: zeppelin

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: zeppelin
    labels:
      name: zeppelin
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      name: zeppelin
    template:
      metadata:
        labels:
          name: zeppelin
      spec:
        containers:
          - name: zeppelin
            image: tsriharsha/openshift-zeppelin
            ports:
              - name: zeppelin-web
                protocol: TCP
                containerPort: 8080
            env:
              - name: SPARK_MASTER_ADDRESS
                value: spark://${SPARK_CLUSTER_NAME}:7077
              - name: SPARK_IMAGE
                value: ${SPARK_CLUSTER_IMAGE}

- kind: Route
  apiVersion: v1
  metadata:
    name: zeppelin-web
    labels:
      name: zeppelin
  spec:
    host:
    to:
      kind: Service
      name: zeppelin-web

parameters:
- name: SPARK_CLUSTER_NAME
  description: Name of spark cluster to run against
  required: true
- name: SPARK_CLUSTER_IMAGE
  description: Full name of the spark image to use when creating clusters
  value: radanalyticsio/openshift-spark
